# Generated by Django 6.0.2 on 2026-02-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='팀명')),
                ('discord_role_id', models.CharField(max_length=50, unique=True, verbose_name='디스코드 역할 ID')),
                ('wins', models.IntegerField(default=0, verbose_name='승리')),
                ('losses', models.IntegerField(default=0, verbose_name='패배')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(max_length=50, unique=True, verbose_name='디스코드 유저 ID')),
                ('riot_id', models.CharField(max_length=100, verbose_name='라이엇 ID')),
                ('tier', models.IntegerField(choices=[(1, '1티어'), (2, '2티어'), (3, '3티어'), (4, '4티어'), (5, '5티어')], verbose_name='티어')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='tournament.team', verbose_name='소속 팀')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(unique=True, verbose_name='경기 번호')),
                ('status', models.CharField(choices=[('PENDING', '대기 중'), ('IN_PROGRESS', '진행 중'), ('COMPLETED', '종료됨')], default='PENDING', max_length=20, verbose_name='경기 상태')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='tournament.team', verbose_name='A팀')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='tournament.team', verbose_name='B팀')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournament.team', verbose_name='승리 팀')),
            ],
        ),
    ]
