# Generated by Django 6.0.2 on 2026-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='디스코드 닉네임'),
        ),
    ]
