# Generated by Django 6.0.2 on 2026-02-28 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_player_discord_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='discord_role_id',
        ),
        migrations.AddField(
            model_name='match',
            name='game_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='게임 소요 시간 (MM:SS)'),
        ),
        migrations.AddField(
            model_name='player',
            name='main_position',
            field=models.CharField(choices=[('TOP', '탑'), ('JUG', '정글'), ('MID', '미드'), ('ADC', '원딜'), ('SUP', '서포터'), ('FILL', '상관없음')], default='FILL', max_length=4, verbose_name='주 포지션'),
        ),
        migrations.AddField(
            model_name='player',
            name='solo_rank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='최신 솔랭 티어 (예: Emerald 2)'),
        ),
        migrations.AddField(
            model_name='player',
            name='sub_position',
            field=models.CharField(choices=[('TOP', '탑'), ('JUG', '정글'), ('MID', '미드'), ('ADC', '원딜'), ('SUP', '서포터'), ('FILL', '상관없음')], default='FILL', max_length=4, verbose_name='부 포지션'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('IN_PROGRESS', '진행 중'), ('COMPLETED', '종료됨')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='tournament.team', verbose_name='팀 A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='tournament.team', verbose_name='팀 B'),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_user_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='디스코드 유저 ID(숫자)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='디스코드 닉네임'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tier',
            field=models.IntegerField(choices=[(1, '1티어'), (2, '2티어'), (3, '3티어'), (4, '4티어'), (5, '5티어')], verbose_name='대회 티어'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='팀명'),
        ),
    ]
