# Generated by Django 6.0.2 on 2026-02-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_team_discord_role_id_match_game_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='highest_rank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='최고 티어 (예: Diamond 4)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='solo_rank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='현재 티어 (예: Emerald 2)'),
        ),
    ]
