# Generated by Django 6.0.2 on 2026-02-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_player_highest_rank_alter_player_solo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='특이사항/노트'),
        ),
    ]
