# Generated by Django 6.0.2 on 2026-02-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_player_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sub_position',
            field=models.CharField(blank=True, choices=[('TOP', '탑'), ('JUG', '정글'), ('MID', '미드'), ('ADC', '원딜'), ('SUP', '서포터'), ('FILL', '상관없음')], max_length=4, null=True, verbose_name='부 포지션'),
        ),
    ]
