# Generated by Django 6.0.2 on 2026-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_player_sub_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='main_position',
            field=models.CharField(choices=[('TOP', '탑'), ('JGL', '정글'), ('MID', '미드'), ('ADC', '원딜'), ('SUP', '서포터'), ('FILL', '상관없음')], default='FILL', max_length=4, verbose_name='주 포지션'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sub_position',
            field=models.CharField(blank=True, choices=[('TOP', '탑'), ('JGL', '정글'), ('MID', '미드'), ('ADC', '원딜'), ('SUP', '서포터'), ('FILL', '상관없음')], max_length=4, null=True, verbose_name='부 포지션'),
        ),
    ]
