# Generated by Django 6.0.2 on 2026-02-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_player_main_position_alter_player_sub_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
