# Generated by Django 6.0.2 on 2026-03-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_match_is_completed_match_screenshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('GROUP', '조별 리그 (Group Stage)'), ('DEATHMATCH', '데스매치 (Quarter Finals)'), ('SEMI', '세미 파이널 (Semi Finals)'), ('FINAL', '결승전 (Finals)')], default='GROUP', max_length=20, verbose_name='경기 스테이지'),
        ),
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'Group A'), ('B', 'Group B')], max_length=1, null=True, verbose_name='소속 그룹'),
        ),
    ]
