# Generated by Django 6.0.2 on 2026-03-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_match_stage_team_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scheduled_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='예정 시간'),
        ),
    ]
