# Generated by Django 6.0.2 on 2026-03-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_match_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_a_score',
            field=models.IntegerField(default=0, verbose_name='팀 A 스코어'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_score',
            field=models.IntegerField(default=0, verbose_name='팀 B 스코어'),
        ),
    ]
