# Generated by Django 6.0.2 on 2026-03-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_match_team_a_score_match_team_b_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader_discord_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
